Docstrings have been changed from numpy to google style
amsehili/genRSS pull request #39
Opened 2022-08-01 08:30 UTC by Vicky-Vicky27

I have changed the docstrings to be in google style rather than numpy style

2022-08-02 20:26 UTC, amsehili requested changes

2022-08-02 20:26 UTC, amsehili commented on genRSS.py
> +<<<<<<< HEAD
This should be removed.

2022-08-02 20:26 UTC, amsehili commented on genRSS.py
> +        ...                  description="This is item 1", pubDate="Mon, 22 Dec 2014 18:30:00 +0000",
`pubDate` argument is now called `pub_date`.

Please run `python genRSS.py --run-tests` after you update the code to make sure the tests pass.

2022-08-02 20:26 UTC, amsehili commented on genRSS.py
> +        indent (string): A string of whitespaces used to indent the elements of the item.
You should use `str` instead of `string` here (and for argument of the same type) as `str` is a class and is the expected type.

2022-08-02 20:26 UTC, amsehili commented on genRSS.py
> +    pubDate (string): Date of publication of the item. Should follow the RFC 822 format,
`pubDate` is now `pub_date`.

2022-08-03 09:43 UTC, Vicky-Vicky27 commented
Thanks for the feedback! I've impemented these changes

2022-08-03 19:18 UTC, merged

2022-08-03 19:19 UTC, amsehili commented
Cool, thanks for your contribution :)